name: "deploy logic app template"

on:
  workflow_dispatch: 
    inputs:
      resourceGroupName: string

jobs:
  deploy-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 
     
      - name: deploy template
        id: deploy
        uses: azure/powershell@v1
        with: 
          inlineScript: |
            az deployment group create -g ${{inputs.resourceGroupName}} --template-file ./templates/template.json 
          azPSVersion: latest
