name: "deploy logic app template"

on:
  workflow_dispatch: 
    inputs:
      logicAppName:
        required: true
      resourceGroupName:
        required: true
      location:
        required: true
      frequency:
        required: true
      interval:
        required: true

jobs:
  deploy-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 
     
      - name: deploy template
        id: deploy
        uses: azure/powershell@v1
        with: 
          inlineScript: |
            az deployment group create -g ${{inputs.resourceGroupName}} --template-file ./templates/template.json --parameters workflows_logic_app_name=${{inputs.logicAppName}} `
                                                                                                                  sites_test_storages_externalid=/subscriptions/${{secrets.SUBSCRIPTION_ID}}/resourceGroups/${{inputs.resourceGroupName}}/providers/Microsoft.Web/sites/func-test-storages `
                                                                                                                  sites_for_each_subscription_function_externalid=/subscriptions/${{secrets.SUBSCRIPTION_ID}}/resourceGroups/${{inputs.resourceGroupName}}/providers/Microsoft.Web/sites/func-for-each-subscription `
                                                                                                                  sites_start_function_externalid=/subscriptions/${{secrets.SUBSCRIPTION_ID}}/resourceGroups/${{inputs.resourceGroupName}}/providers/Microsoft.Web/sites/func-start-function `
                                                                                                                  sites_end_function_externalid=/subscriptions/${{secrets.SUBSCRIPTION_ID}}/resourceGroups/${{inputs.resourceGroupName}}/providers/Microsoft.Web/sites/func-end-function 
                                                                                                                  sites_log_analytics_function_app_externalid=/subscriptions/${{secrets.SUBSCRIPTION_ID}}/resourceGroups/${{inputs.resourceGroupName}}/providers/Microsoft.Web/sites/func-log-analytics `
                                                                                                                  connections_office365_1_externalid=/subscriptions/${{secrets.SUBSCRIPTION_ID}}/resourceGroups/${{inputs.resourceGroupName}}/providers/Microsoft.Web/connections/office365-1 `
                                                                                                                  location=${{inputs.location}} `
                                                                                                                  frequency=${{inputs.frequency}} `
                                                                                                                  interval=${{inputs.interval}}
          azPSVersion: latest




        # {% comment %} "subscription_id": {
        #     "defaultValue": "a173eef2-33d7-4d55-b0b5-18b271f8d42b",
        #     "type":"string"
        # }, {% endcomment %}
        # {% comment %} "function_app_resource_group_name":{
        #     "defaultValue": "NetworkWatcherRG",
        #     "type":"string"
        # },
        # "function_app_names":{
        #     "defaultValue": ["func-log-analytics","func-start-function","func-for-each-subscription","func-test-storages","func-end-function"],
        #     "type":"array"
        # } {% endcomment %}